version: '3.3'

services:
  mongo-server:
    container_name: mongo-server
    ports:
      - 27017:27017
    image: mongo:4.4.6
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=test001
      - MONGO_INITDB_DATABASE=test
      - MONGO_USERNAME=dgkwon
      - MONGO_PASSWORD=test001
    volumes:
      - ./mongo-server/data:/data/db
      - ./mongo-server/init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh:ro

  mongo-server-express:
    container_name: mongo-server-express
    ports:
      - 8081:8081
    image: mongo-express
    restart: always
    environment:
      - ME_CONFIG_BASICAUTH_USERNAME=dgkwon
      - ME_CONFIG_BASICAUTH_PASSWORD=test001
      - ME_CONFIG_MONGODB_SERVER=mongo-server
      - ME_CONFIG_PORT=27017
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=test001
    depends_on:
      - mongo-server

  rabbitmq-server:
    container_name: rabbitmq-server
    ports:
      - 5672:5672
      - 15672:15672
    image: rabbitmq:3-management-alpine
    restart: always
    environment: 
      - RABBITMQ_DEFAULT_USER=dgkwon
      - RABBITMQ_DEFAULT_PASS=test001
    volumes:
      - ./rabbitmq-server/etc/:/etc/rabbitmq/
      - ./rabbitmq-server/data/:/var/lib/rabbitmq/
      - ./rabbitmq-server/logs/:/var/log/rabbitmq/

  redis-server:
    container_name: redis-server
    ports:
      - 6379:6379
    image: redis:7.0.0-alpine
    restart: always
    labels:
      - "name=redis"
      - "mode=standalone"
    volumes:
      - ./redis-server/data:/data:rw
      - ./redis-server/etc/redis.conf:/etc/redis.conf:rw
    command: redis-server /etc/redis.conf

  redis-insight:
    container_name: redis-insight
    ports:
      - '8001:8001'
    image: redislabs/redisinsight:1.12.1
    restart: always
    volumes:
      - ./redis-insight/data:/db
    depends_on:
      - redis-server

  mariadb-server:
    container_name: mariadb-server
    ports: 
      - 3306:3306
    image: mariadb:10.6.5
    restart: always
    environment: 
      - MARIADB_DATABASE=test001
      - MARIADB_USER=dgkwon
      - MARIADB_PASSWORD=test001
      - MARIADB_ROOT_PASSWORD=test001
    volumes:
      - ./mariadb-server/data:/var/lib/mysql:rw
      - ./mariadb-server/conf.d:/etc/mysql/conf.d:rw

    
