version: '3.3'

services:
  mongo-server:
    container_name: mongo-server
    ports:
      - 27017:27017
    image: mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=test001
      - MONGO_INITDB_DATABASE=test
      - MONGO_USERNAME=dgkwon
      - MONGO_PASSWORD=test001
    volumes:
      - ./mongo-server/data:/data/db
      - ./mongo-server/init-mongo-v6.0.sh:/docker-entrypoint-initdb.d/init-mongo.sh:ro

  mongo-server-express:
    container_name: mongo-server-express
    ports:
      - 8081:8081
    image: mongo-express
    restart: always
    environment:
      - ME_CONFIG_BASICAUTH_USERNAME=dgkwon
      - ME_CONFIG_BASICAUTH_PASSWORD=test001
      - ME_CONFIG_MONGODB_SERVER=mongo-server
      - ME_CONFIG_PORT=27017
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=test001
    depends_on:
      - mongo-server

  rabbitmq-server:
    container_name: rabbitmq-server
    ports:
      - 5672:5672
      - 15672:15672
    image: rabbitmq:3-management-alpine
    restart: always
    environment: 
      - RABBITMQ_DEFAULT_USER=dgkwon
      - RABBITMQ_DEFAULT_PASS=test001
    volumes:
      - ./rabbitmq-server/etc/:/etc/rabbitmq/
      - ./rabbitmq-server/data/:/var/lib/rabbitmq/
      - ./rabbitmq-server/logs/:/var/log/rabbitmq/

  redis-server:
    container_name: redis-server
    ports:
      - 7480:7480
    image: redis:7.0.0-alpine
    restart: always
    labels:
      - "name=redis"
      - "mode=standalone"
    volumes:
      - ./redis/data:/data:rw
    command: redis-server --port 7480 --requirepass "test001"

  redis-insight:
    container_name: redis-insight
    ports:
      - '8001:8001'
    image: redislabs/redisinsight:1.12.1
    volumes:
      - ./redis-insight/data:/db
