version: '3.3'

services:
  mongo-server:
    container_name: mongo-server
    ports:
      - 27017:27017
    image: mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=test001
      - MONGO_INITDB_DATABASE=test
      - MONGO_USERNAME=dgkwon
      - MONGO_PASSWORD=test001
    volumes:
      - ./mongo-server/data:/data/db
      - ./mongo-server/init-mongo-v6.0.sh:/docker-entrypoint-initdb.d/init-mongo.sh:ro

  mongo-server-express:
    container_name: mongo-server-express
    ports:
      - 8081:8081
    image: mongo-express
    restart: always
    environment:
      - ME_CONFIG_BASICAUTH_USERNAME=dgkwon
      - ME_CONFIG_BASICAUTH_PASSWORD=test001
      - ME_CONFIG_MONGODB_SERVER=mongo-server
      - ME_CONFIG_PORT=27017
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=test001
    depends_on:
      - mongo-server
